# Generated by Django 2.2.14 on 2021-06-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetailes',
            name='shorted_url',
            field=models.SlugField(),
        ),
    ]
