# Generated by Django 3.2.4 on 2021-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210628_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetailes',
            name='shorted_url',
            field=models.CharField(max_length=15),
        ),
    ]
