# Generated by Django 3.2.4 on 2021-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_alter_urldetailes_shorted_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetailes',
            name='shorted_url',
            field=models.SlugField(max_length=15),
        ),
    ]
